### ISSUE TITLE
ImportError: libsteam.so.1

### ISSUE THREAD

**Issue by DJNing** [utiasASRL/hero_radar_odometry#24]
Hello, I build the docker following your instructions. But when I try to run the train.py, it raises this issue:

Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from networks.hero import HERO
  File "/workspace/hero_radar_odometry/networks/hero.py", line 9, in <module>
    from networks.steam_solver import SteamSolver
  File "/workspace/hero_radar_odometry/networks/steam_solver.py", line 3, in <module>
    import cpp.build.SteamSolver as steamcpp
ImportError: /usr/local/lib/libsteam.so.1: undefined symbol: _ZN5boost6system16generic_categoryEv

I use cuda11.1-cudnn8-runtime for the compatability on GTX3090, would this be a matter?

**Comment by keenan-burnett** [comment]
Are you running this within the docker?
Make sure that you're building the c++ code within the docker container.
Try deleting the cpp/build folder and build the c++ code again from scratch within the docker container.

I don't think your cudnn setup on the host machine is related to this.
It seems like something has happened during the c++ build process that might be related to the boost library.

**Comment by DJNing** [comment]
Yes, I am running every thing within the docker. The steam library is install during docker build right? Do you suggest me to re-build steam within the container?

**Comment by keenan-burnett** [comment]
Can you share your modified dockerfile to see if I can reproduce the issue?
Also, what is your host operating system?

**Comment by DJNing** [comment]
[Dockerfile.txt](https://github.com/utiasASRL/hero_radar_odometry/files/6666984/Dockerfile.txt)

Sure, the docker file is in the attachment

**Comment by keenan-burnett** [comment]
Okay, I replicated the error that you got.
It is definitely due to the one line that you changed in the Dockerfile:
`FROM nvcr.io/nvidia/cuda:11.1-cudnn8-runtime`

I noticed that this uses a completely different version of python: 3.8.5, whereas our docker is running 3.6.9

So this change breaks a few things:

- The CMakeLists is expecting python36 numpy36, this has to be changed to python38, numpy38
- You'll need to use a newer version of boost since 1.67 only supports up to python 3.6, you could try the latest version (1.76) but I don't know if that might cause other issues. You can update the Dockerfile for your purpose to use this download  link instead: `https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz` and update all references to 1.67 to 1.76.

Let me know if these changes fix your problems. If not, please try the original dockerfile and see if it works for you.

**Comment by DJNing** [comment]
Thank you very much for the reply!

**Comment by keenan-burnett** [comment]
Okay, I managed to get it working with a modified version of your Dockerfile.

You'll need to rebuild your docker image with a newer version of boost:

Replace lines 34-41 in the Dockerfile with the following:

```
RUN cd /usr/src && \
 wget --no-verbose https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz && \
 tar xzf boost_1_76_0.tar.gz && \
 cd boost_1_76_0 && \
 ./bootstrap.sh --with-python=$(which python3) && \
 ./b2 cxxflags="-std=gnu++17" install && \
 ldconfig && \
 cd / && rm -rf /usr/src/*
```

Rebuild your docker image after this change is put in.

Then, proceed as before with building the C++ code, however you'll need to make the following change to `CMakeLists.txt`

change line 21 in `CMakeLists.txt` to:
`find_package(Boost COMPONENTS python38 numpy38 system)`

**Comment by keenan-burnett** [comment]
I recently updated the repo to fix some bugs in my UnderTheRadar implementation. You may want to pull those changes. Also, I trained new version of my implementation to completion. I was able to get 3.08 % Terr and 10.7 deg/1000m with this undertheradar implementation. You can download this and my other pre-trained models with the `download_models.sh` script. 

Cheers
