### ISSUE TITLE
test on automotive radar datasets

### ISSUE THREAD

**Issue by izzat1** [utiasASRL/hero_radar_odometry#25]
Thanks for sharing the code of your work. Did you have a chance to test the code on other datasets like https://www.nuscenes.org/
which uses automotive radars?

**Comment by keenan-burnett** [comment]
No, I haven't yet tested hero on the nuscenes dataset. This algorithm was designed to be used on radar sensors that provide the full waveform, that is an intensity for each range bin for each scanned azimuth. From my understanding, the radar that nuscenes provides is in the form of sparse targets which contain less information than can be extracted using a sensor like the Navtech. It's still possible to run hero on this data, but it would require first transforming the sparse targets into a top-down cartesian representation in order to minimize the code changes within this repo.

**Comment by izzat1** [comment]
The sparsity of the data may prevent the algorithm from working probably but it certainly worth trying. Thanks for you comments.
