### ISSUE TITLE
Some question about code and paper

### ISSUE THREAD

**Issue by Yeah2333** [utiasASRL/hero_radar_odometry#28]
@keenan-burnett Hi, thank you for your code and paper. I have some question about code and paper. 

1. I have test hero, and val metric is t_err: 2.031, r_err: 6.329. But when test UnderTheRadar, the best val metric is t_err: 3.712, r_err:10.96. This result is quite different from hero paper. I use default config in radar.json. What causes this?
2. In steam solver cpp code, i can find measurement factor code.
https://github.com/utiasASRL/hero_radar_odometry/blob/04bd6717db57d1f003066f5318be7fd213d50afc/cpp/SteamSolver.cpp#L175
But i can't find motion prior factors, the only thing about this is :
https://github.com/utiasASRL/hero_radar_odometry/blob/04bd6717db57d1f003066f5318be7fd213d50afc/cpp/SteamSolver.cpp#L82
Could you tell me more about the code of motion prior factor?
3. In steam config, "zero_vel_prior" and "vel_prior" means what? I can't understand this code in SteamSolver.cpp.

**Comment by keenan-burnett** [comment]
1. I wasn't able to replicate the performance of the UnderTheRadar implementation. Note that their paper does not include an open-source implementation, this was simply my best effort at replicating their results. If I had to guess, I think it is important to improve the rotation augmentation during training so that one starts with the road at $\theta$ degrees offset from the default and then add another smaller perturbation to the matched radar image $\delta\theta$. This is different from how I did the rotation augmentation in this repo, but may improve the results. Also, it's quite possible that I simply didn't train the model for long enough. Try training it with larger batch sizes and for many more epochs and see if that improves results.

2. The motion prior factors are added to the costTerms object at this line of code:

https://github.com/utiasASRL/hero_radar_odometry/blob/04bd6717db57d1f003066f5318be7fd213d50afc/cpp/SteamSolver.cpp#L108

The mathematical details of which are contained in this paper:
https://ieeexplore.ieee.org/abstract/document/7353368/

Have a look at equation (15) in that paper.

3. The `zero_vel_prior` is used to ensure that the dimensions outside of SE(2) remain zero. In theory this shouldn't be needed, however there was some concern that mathematical rounding errors in the computer could lead to small velocities in the dimensions outside of SE(2) which would lead to a bias. This prior then encourages the velocities outside of SE(2) to stay close to zero. It shouldn't have much of an impact whether it is turned on or not.

`vel_prior` adds a cost term to the estimation so that we penalize a velocity estimate which differs from the previously estimated velocity:

$$
\mathbf{e}_{\text{vel prior}} = \boldsymbol{\varpi} - \boldsymbol{\varpi}_{\text{prev}}
$$

**Comment by Yeah2333** [comment]
Sorry for late reply. 

1.  I will test this aug method later. And I have found when set sigmod of score output， the performance of hero will be worse. 
<img width="799" alt="image" src="https://user-images.githubusercontent.com/22851247/212539078-8be39505-4a07-4f42-a019-bb2ddf7bb44d.png">
2. Thank you very much. I have find this factor code in steam repo. 
https://github.com/utiasASRL/steam/blob/8ed9b43acfd07f1544043adb0ab93b30754b5269/src/trajectory/SteamTrajInterface.cpp#L260


3. "vel_prior" adds a cost term to the estimation so that we penalize a velocity estimate which differs from the previously estimated velocity: This means when vel_prior to true, in test stage, post window can using velocity that previous window result as a prior factor ?
